### ISSUE TITLE
Update with upstream

### ISSUE THREAD

**Issue by marashiai** [mercmobily/JS-Interpreter#2]
It's been a while since this package is updated, we will need to update with the mainstream repo and mention in the documentations that this is not an official Google NPM package.

**Comment by hsluoyz** [comment]
Thanks for updating it! It helps!

**Comment by marashiai** [comment]
Published [version 2.0.0](https://www.npmjs.com/package/js-interpreter).

**Comment by hsluoyz** [comment]
Thanks!
